### ISSUE TITLE
Network Policies before ResourceLocker namespaces labels applied

### ISSUE THREAD

**Issue by megian** [projectsyn/component-networkpolicy#6]
We had an timing issue occurred because of the network policies have been applied, before the namespace labels
```
    network-policies.syn.tools/no-defaults: "true"
    network-policies.syn.tools/purge-defaults: "true"
```
have been three. This caused several APIs haven't been accessible:
```
$ oc api-resources
error: unable to retrieve the complete list of server APIs: apps.openshift.io/v1: the server is currently unable to handle the request, authorization.openshift.io/v1: the server is currently unable to handle the request, image.openshift.io/v1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: the server is currently unable to handle the request, oauth.openshift.io/v1: the server is currently unable to handle the request, project.openshift.io/v1: the server is currently unable to handle the request, quota.openshift.io/v1: the server is currently unable to handle the request, route.openshift.io/v1: the server is currently unable to handle the request, template.openshift.io/v1: the server is currently unable to handle the request
```

## Steps to Reproduce the Problem

  1. Set up a fresh cluster
  1. Apply the component networkpolicy

## Actual Behavior
There is a timing issue, that Espejo might be faster than the ResourceLocker causing this issue.

## Expected Behavior
There is a clear dependency, that only if the labels have been set, Espejo is going to create the network policies.

**Comment by mhutter** [comment]
In new clusters, this completely breaks the cluster because it also prevents access to the internal DNS server.

**Comment by mhutter** [comment]
Suggestion:
1. Update the component to use [ignoreNames](https://github.com/vshn/espejo/blob/ca4a61a6fe0a2d2ba1b92314b6416bb382669027/config/crd/apiextensions.k8s.io/v1/base/sync.appuio.ch_syncconfigs.yaml#L70-L71) instead
2. Ignore all `openshift-*` and `kube-*` namespaces
